name: Generate snake game SVG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate snake svg
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: TheBunnyMan123
          outputs: |
            dist/dark.svg?palette=github-dark&color_snake=blue
            dist/light.svg?color_snake=#7845ab
        
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: images
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
